### ISSUE TITLE
Additional Text/Tags Added While Saving Are Ignored

### ISSUE THREAD

**Issue by Logan1x** [tryunearth/app#11]
When I am adding a tag, just after added one, then tag box is getting closed. To add new tag I have to open the tag icon again. Have a look at it here,  ([imgur link](https://i.imgur.com/NjEnWnA.gif))

![image](https://i.imgur.com/NjEnWnA.gif)

**Comment by cedricium** [comment]
Hey @Logan1x, thanks for raising this issue. The problem is as follows:

- when clicking the "Save" button, a request is made to the API, submitting any text in the input field as a tag
- in between the time from clicking save to when the API request is complete, the "Edit Tags" modal is still displayed
- typing anything in the input field after clicking save then is ignored as the API request is already

There are a couple possible solutions I can think of:

- while the request is in progress, disable the input field so no further text can be added, OR
- immediately close the "Edit Tags" modal after hitting "Save" (this seems to be how Pocket does it)
